name: Simplus
favicon: null
layout_spectrum: 0.74708
typography_spectrum: 0.65555
title: SIMPLUS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e95e49'
    - '#cdd662'
    - '#3c9eba'
    - '#afa561'
  brandStrength: 0.75
  lightness: 0.02927701734006405
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
